<?php
/**
 * Implements hook_preprocess_block().
 */
// kint code below works for d8 but is different in d9
// start - when using kint(), uncomment these lines to keep it from providing too much data
// kint_require();
// Kint::$maxLevels = 8;
// end - when using kint(), uncomment these lines to keep it from providing too much data

function laurel_preprocess_block(array &$variables) {
  // start - reveal plugin_id values needed in block style plugins config
  // print '<pre>' . $variables['plugin_id'] . '</pre>';
  // end - reveal plugin_id values needed in block style plugins config
}

/**
 * Implements hook_page_attachments_alter() to remove generator metatag.
 */
function laurel_page_attachments_alter(array &$attachments) {
  foreach ($attachments['#attached']['html_head'] as $key => $attachment) {
    if ($attachment[1] == 'system_meta_generator') {
      unset($attachments['#attached']['html_head'][$key]);
    }
  }
}